# Generated by Django 4.0.2 on 2022-03-09 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('snippet_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=5000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
